### ISSUE TITLE
Can you provide the output from running Cake with Diagnostic Verbosity?

### ISSUE THREAD

**Issue by gep13** [mattfrear/CakeFail#1]
@mattfrear thanks!

**Comment by mattfrear** [comment]
```
PS C:\code\github\CakeFail> .\build.ps1 -verbosity diagnostic
Preparing to run build script...
Running build script...
Module directory does not exist.
Analyzing build script...
Analyzing C:/code/github/CakeFail/build.cake...
Processing build script...
Installing tools...
Package xunit.runner.console has already been installed.
Installing addins...
Package Cake.Incubator has already been installed.
The addin Cake.Incubator will reference Cake.Incubator.dll.
Package Cake.AutoRest has already been installed.
The addin Cake.AutoRest will reference Cake.AutoRest.dll.
Creating script session...
Adding reference to mscorlib.dll...
Adding reference to System.Core.dll...
Adding reference to Cake.Core.dll...
Adding reference to Cake.Common.dll...
Adding reference to Cake.exe...
Adding reference to System.dll...
Adding reference to System.Xml.dll...
Adding reference to System.Xml.Linq.dll...
Adding reference to System.Data.dll...
Adding reference to Cake.Incubator.dll...
Adding reference to Cake.AutoRest.dll...
Importing namespace Cake.AutoRest...
Importing namespace Cake.Common...
Importing namespace Cake.Common.Build...
Importing namespace Cake.Common.Build.AppVeyor...
Importing namespace Cake.Common.Build.AppVeyor.Data...
Importing namespace Cake.Common.Build.Bamboo...
Importing namespace Cake.Common.Build.Bamboo.Data...
Importing namespace Cake.Common.Build.BitbucketPipelines...
Importing namespace Cake.Common.Build.BitbucketPipelines.Data...
Importing namespace Cake.Common.Build.Bitrise...
Importing namespace Cake.Common.Build.Bitrise.Data...
Importing namespace Cake.Common.Build.ContinuaCI...
Importing namespace Cake.Common.Build.ContinuaCI.Data...
Importing namespace Cake.Common.Build.GitLabCI...
Importing namespace Cake.Common.Build.GitLabCI.Data...
Importing namespace Cake.Common.Build.GoCD...
Importing namespace Cake.Common.Build.GoCD.Data...
Importing namespace Cake.Common.Build.Jenkins...
Importing namespace Cake.Common.Build.Jenkins.Data...
Importing namespace Cake.Common.Build.MyGet...
Importing namespace Cake.Common.Build.TeamCity...
Importing namespace Cake.Common.Build.TFBuild...
Importing namespace Cake.Common.Build.TFBuild.Data...
Importing namespace Cake.Common.Build.TravisCI...
Importing namespace Cake.Common.Build.TravisCI.Data...
Importing namespace Cake.Common.Diagnostics...
Importing namespace Cake.Common.IO...
Importing namespace Cake.Common.IO.Paths...
Importing namespace Cake.Common.Net...
Importing namespace Cake.Common.Security...
Importing namespace Cake.Common.Solution...
Importing namespace Cake.Common.Solution.Project...
Importing namespace Cake.Common.Solution.Project.Properties...
Importing namespace Cake.Common.Solution.Project.XmlDoc...
Importing namespace Cake.Common.Text...
Importing namespace Cake.Common.Tools...
Importing namespace Cake.Common.Tools.Cake...
Importing namespace Cake.Common.Tools.Chocolatey...
Importing namespace Cake.Common.Tools.Chocolatey.ApiKey...
Importing namespace Cake.Common.Tools.Chocolatey.Config...
Importing namespace Cake.Common.Tools.Chocolatey.Download...
Importing namespace Cake.Common.Tools.Chocolatey.Features...
Importing namespace Cake.Common.Tools.Chocolatey.Install...
Importing namespace Cake.Common.Tools.Chocolatey.New...
Importing namespace Cake.Common.Tools.Chocolatey.Pack...
Importing namespace Cake.Common.Tools.Chocolatey.Pin...
Importing namespace Cake.Common.Tools.Chocolatey.Push...
Importing namespace Cake.Common.Tools.Chocolatey.Sources...
Importing namespace Cake.Common.Tools.Chocolatey.Uninstall...
Importing namespace Cake.Common.Tools.Chocolatey.Upgrade...
Importing namespace Cake.Common.Tools.DotCover...
Importing namespace Cake.Common.Tools.DotCover.Analyse...
Importing namespace Cake.Common.Tools.DotCover.Cover...
Importing namespace Cake.Common.Tools.DotCover.Merge...
Importing namespace Cake.Common.Tools.DotCover.Report...
Importing namespace Cake.Common.Tools.DotNetCore...
Importing namespace Cake.Common.Tools.DotNetCore.Build...
Importing namespace Cake.Common.Tools.DotNetCore.Clean...
Importing namespace Cake.Common.Tools.DotNetCore.Execute...
Importing namespace Cake.Common.Tools.DotNetCore.MSBuild...
Importing namespace Cake.Common.Tools.DotNetCore.NuGet.Delete...
Importing namespace Cake.Common.Tools.DotNetCore.NuGet.Push...
Importing namespace Cake.Common.Tools.DotNetCore.Pack...
Importing namespace Cake.Common.Tools.DotNetCore.Publish...
Importing namespace Cake.Common.Tools.DotNetCore.Restore...
Importing namespace Cake.Common.Tools.DotNetCore.Run...
Importing namespace Cake.Common.Tools.DotNetCore.Test...
Importing namespace Cake.Common.Tools.DotNetCore.Tool...
Importing namespace Cake.Common.Tools.DotNetCore.VSTest...
Importing namespace Cake.Common.Tools.DupFinder...
Importing namespace Cake.Common.Tools.Fixie...
Importing namespace Cake.Common.Tools.GitLink...
Importing namespace Cake.Common.Tools.GitReleaseManager...
Importing namespace Cake.Common.Tools.GitReleaseManager.AddAssets...
Importing namespace Cake.Common.Tools.GitReleaseManager.Close...
Importing namespace Cake.Common.Tools.GitReleaseManager.Create...
Importing namespace Cake.Common.Tools.GitReleaseManager.Export...
Importing namespace Cake.Common.Tools.GitReleaseManager.Publish...
Importing namespace Cake.Common.Tools.GitReleaseNotes...
Importing namespace Cake.Common.Tools.GitVersion...
Importing namespace Cake.Common.Tools.ILMerge...
Importing namespace Cake.Common.Tools.ILRepack...
Importing namespace Cake.Common.Tools.InnoSetup...
Importing namespace Cake.Common.Tools.InspectCode...
Importing namespace Cake.Common.Tools.MSBuild...
Importing namespace Cake.Common.Tools.MSTest...
Importing namespace Cake.Common.Tools.NSIS...
Importing namespace Cake.Common.Tools.NuGet...
Importing namespace Cake.Common.Tools.NuGet.Add...
Importing namespace Cake.Common.Tools.NuGet.Init...
Importing namespace Cake.Common.Tools.NuGet.Install...
Importing namespace Cake.Common.Tools.NuGet.Pack...
Importing namespace Cake.Common.Tools.NuGet.Push...
Importing namespace Cake.Common.Tools.NuGet.Restore...
Importing namespace Cake.Common.Tools.NuGet.SetApiKey...
Importing namespace Cake.Common.Tools.NuGet.SetProxy...
Importing namespace Cake.Common.Tools.NuGet.Sources...
Importing namespace Cake.Common.Tools.NuGet.Update...
Importing namespace Cake.Common.Tools.NUnit...
Importing namespace Cake.Common.Tools.OctopusDeploy...
Importing namespace Cake.Common.Tools.OpenCover...
Importing namespace Cake.Common.Tools.ReportGenerator...
Importing namespace Cake.Common.Tools.ReportUnit...
Importing namespace Cake.Common.Tools.Roundhouse...
Importing namespace Cake.Common.Tools.SignTool...
Importing namespace Cake.Common.Tools.SpecFlow...
Importing namespace Cake.Common.Tools.SpecFlow.StepDefinitionReport...
Importing namespace Cake.Common.Tools.SpecFlow.TestExecutionReport...
Importing namespace Cake.Common.Tools.TextTransform...
Importing namespace Cake.Common.Tools.VSTest...
Importing namespace Cake.Common.Tools.VSWhere...
Importing namespace Cake.Common.Tools.VSWhere.All...
Importing namespace Cake.Common.Tools.VSWhere.Latest...
Importing namespace Cake.Common.Tools.VSWhere.Legacy...
Importing namespace Cake.Common.Tools.VSWhere.Product...
Importing namespace Cake.Common.Tools.WiX...
Importing namespace Cake.Common.Tools.WiX.Heat...
Importing namespace Cake.Common.Tools.XBuild...
Importing namespace Cake.Common.Tools.XUnit...
Importing namespace Cake.Common.Xml...
Importing namespace Cake.Core...
Importing namespace Cake.Core.Diagnostics...
Importing namespace Cake.Core.IO...
Importing namespace Cake.Core.Scripting...
Importing namespace Cake.Incubator...
Importing namespace System...
Importing namespace System.Collections.Generic...
Importing namespace System.IO...
Importing namespace System.Linq...
Importing namespace System.Text...
Importing namespace System.Threading.Tasks...
Compiling build script...

========================================
Clean
========================================
Executing task: Clean
Cleaning directory C:/code/github/CakeFail/artifacts
Finished executing task: Clean

========================================
NuGet-Restore
========================================
Executing task: NuGet-Restore
Executing: "C:/Program Files (x86)/NuGet/NuGet.exe" restore "C:/code/github/CakeFail/CakeFail.sln" -NonInteractive
MSBuild auto-detection: using msbuild version '15.1.1012.6693' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.
Restoring packages for C:\code\github\CakeFail\src\NetCore\NetCore.csproj...
Restoring packages for C:\code\github\CakeFail\src\NetFramework\NetFramework.csproj...
Committing restore...
Generating MSBuild file C:\code\github\CakeFail\src\NetFramework\obj\NetFramework.csproj.nuget.g.props.
Writing lock file to disk. Path: C:\code\github\CakeFail\src\NetFramework\obj\project.assets.json
Committing restore...
Generating MSBuild file C:\code\github\CakeFail\src\NetCore\obj\NetCore.csproj.nuget.g.props.
Restore completed in 1.09 sec for C:\code\github\CakeFail\src\NetFramework\NetFramework.csproj.
Writing lock file to disk. Path: C:\code\github\CakeFail\src\NetCore\obj\project.assets.json
Restore completed in 1.21 sec for C:\code\github\CakeFail\src\NetCore\NetCore.csproj.

NuGet Config files used:
    C:\Users\matt\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    https://api.nuget.org/v3/index.json
    https://proget.services.kingsway.asos.com/nuget/ASOS
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
Finished executing task: NuGet-Restore

========================================
DotNetCoreRestore
========================================
Executing task: DotNetCoreRestore
Executing: "C:/Program Files/dotnet/dotnet.exe" restore "CakeFail.sln" /p:Version=1.0.0-local
  Restoring packages for C:\code\github\CakeFail\src\NetCore\NetCore.csproj...
  Restoring packages for C:\code\github\CakeFail\src\NetFramework\NetFramework.csproj...
  Generating MSBuild file C:\code\github\CakeFail\src\NetFramework\obj\NetFramework.csproj.nuget.g.props.
  Writing lock file to disk. Path: C:\code\github\CakeFail\src\NetFramework\obj\project.assets.json
  Restore completed in 167.35 ms for C:\code\github\CakeFail\src\NetFramework\NetFramework.csproj.
  Generating MSBuild file C:\code\github\CakeFail\src\NetCore\obj\NetCore.csproj.nuget.g.props.
  Writing lock file to disk. Path: C:\code\github\CakeFail\src\NetCore\obj\project.assets.json
  Restore completed in 522.23 ms for C:\code\github\CakeFail\src\NetCore\NetCore.csproj.

  NuGet Config files used:
      C:\Users\matt\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://api.nuget.org/v3/index.json
      https://proget.services.kingsway.asos.com/nuget/ASOS
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
Finished executing task: DotNetCoreRestore

========================================
Build
========================================
Executing task: Build
Executing: "C:/Program Files/dotnet/dotnet.exe" build "CakeFail.sln" --configuration Release /p:Version=1.0.0-local
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Class1.cs(1,7): error CS0246: The type or namespace name 'LanguageExt' could not be found (are you missing a using directive or an assembly reference?) [C:\code\github\CakeFail\src\NetFramework\NetFramework.csproj]
  NetCore -> C:\code\github\CakeFail\src\NetCore\bin\Release\netcoreapp1.1\NetCore.dll

Build FAILED.

Class1.cs(1,7): error CS0246: The type or namespace name 'LanguageExt' could not be found (are you missing a using directive or an assembly reference?) [C:\code\github\CakeFail\src\NetFramework\NetFramework.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.75
An error occurred when executing task 'Build'.
Error: Cake.Core.CakeException: .NET Core CLI: Process returned an error (exit code 1).
   at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction)
   at Cake.Common.Tools.DotNetCore.Build.DotNetCoreBuilder.Build(String project, DotNetCoreBuildSettings settings)
   at Submission#0.<.ctor>b__8()
   at Cake.Core.ActionTask.Execute(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
   at Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
   at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)
   at Cake.Scripting.BuildScriptHost.RunTarget(String target)
   at Submission#0..ctor(Session session, Object& submissionResult)
   at Submission#0.<Factory>(Session session)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
PS C:\code\github\CakeFail>
```

**Comment by gep13** [comment]
@mattfrear and to confirm....

If you run this command:

`C:/Program Files/dotnet/dotnet.exe" build "CakeFail.sln" --configuration Release /p:Version=1.0.0-local`

Directly at the command line, i.e. taking Cake out of the equation, you get the same result, correct?

**Comment by mattfrear** [comment]
That is correct.

**Comment by gep13** [comment]
@mattfrear okay.  In which case, this is looking more and more like a straight up `dotnet` CLI issue, rather than an issue with Cake.

**Comment by mattfrear** [comment]
OK, thanks @gep13 . I'm not sure where to point this then, because I'm not using the latest dotnet SDK 2.0, because it screws up compilation for our .NET Framework apps: https://developercommunity.visualstudio.com/content/problem/95070/could-not-load-file-or-assembly-systemruntime-vers.html

I'm still using dotnet SDK 1.0.4

Guess I'll stick to packages.config for now since they work with my current toolset.

**Comment by gep13** [comment]
@mattfrear sounds like a plan.

I have seen a couple of threads along the same lines of this 😢 Sounds like there are some known issues in this area.
